# This workflow will run tests using node.

name: build-runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/modular'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        env:
          TOKEN: ${{ secrets.TOKEN }}
          USER: ${{ secrets.USER }}
