name: Workflow for Codecov example-javascript
on: [push, pull_request, workflow_dispatch]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run tests and collect coverage
        run: |
          npm run test
          # Add debugging steps to print out coverage report or check for errors
          ls -l coverage  # Print out contents of the coverage directory
          cat coverage/lcov.info  # Print out the contents of the coverage report file
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4-beta
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
